version: '3'
services:
  mongodb:
    image: mongo
    container_name: MONGO
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - 27017:27017
